io.github.trquinn76.classification.production.mode = false

io.github.trquinn76.classification.usa.development.unclassified.name = Development-UNCLASSIFIED
io.github.trquinn76.classification.usa.development.restricted.name = Development-RESTRICTED
io.github.trquinn76.classification.usa.development.confidential.name = Development-CONFIDENTIAL
io.github.trquinn76.classification.usa.development.secret.name = Development-SECRET
io.github.trquinn76.classification.usa.development.top.secret.name = Development-TOP SECRET

io.github.trquinn76.classification.usa.development.sci.prefix = Devel-
io.github.trquinn76.classification.usa.development.sap.prefix = Devel-
